steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions', 'deploy', 'ComputePricelistHistories',
      '--runtime', 'go111',
      '--trigger-topic', 'computePricelistHistories',
      '--source', '.',
      '--memory', '512M',
      '--region', 'us-central1',
      '--timeout', '120s'
    ]
